"""Added last_update attribute

Revision ID: 115ae284a09a
Revises: 17541a5c4950
Create Date: 2026-05-04 17:36:17.720450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '115ae284a09a'
down_revision: Union[str, Sequence[str], None] = '17541a5c4950'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('last_update', sa.DateTime(), nullable=False))
    op.add_column('platform', sa.Column('last_update', sa.DateTime(), nullable=False))
    op.add_column('review', sa.Column('last_update', sa.DateTime(), nullable=False))
    op.add_column('tag', sa.Column('last_update', sa.DateTime(), nullable=False))
    op.add_column('user_account', sa.Column('last_update', sa.DateTime(), nullable=False))
    op.add_column('user_profile', sa.Column('last_update', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'last_update')
    op.drop_column('user_account', 'last_update')
    op.drop_column('tag', 'last_update')
    op.drop_column('review', 'last_update')
    op.drop_column('platform', 'last_update')
    op.drop_column('game', 'last_update')
    # ### end Alembic commands ###
